#!/bin/bash

  sudo apt update -y

echo "STEP1: install JDK 11"
  sudo apt install openjdk-11-jdk -y

echo "STEP2:add Apt keep to jenkins"
  curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

echo "STEP3 add jenkins:"
  echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

echo "STEP4 update apt again:"
  sudo apt update -y

echo "STEP5 final install jenkins:"
  sudo apt install jenkins -y
